name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      
      # Example 2
      - name: Get file names under check
        id: social-files
        run: |
          social_files=$(cat ./.github/social.txt)
          echo "$social_files"
          echo 'FILES<<EOF' >> $GITHUB_ENV
          echo "$social_files" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Test files
        run: echo "${{ env.FILES }}"

      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v29.0.7
        with:
          files: |
            ${{ env.FILES }}

      - name: Run step if any file(s) in the docs folder change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "One or more files in the docs folder has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"